version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: index
    ports:
      - "800:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
